### ISSUE TITLE
appLayout.querySelector is not a function

### ISSUE THREAD

**Issue by Camatobe** [TheLastProject/lovelace-media-art-background#10]
URL/community_plugin/lovelace-media-art-background/media-art-background.js:30:30 Uncaught TypeError: appLayout.querySelector is not a function

URL/community_plugin/lovelace-media-art-background/media-art-background.js:65:12 Uncaught TypeError: Cannot read property 'style' of null

This 2 Errors are irregularly showing up in my log and my js dev console in the frontend.

I think they are related. querySelector seems not to work anymore?
It was working with 0.103 I guess. 

I am using Core 0.105.2
Installed your plugin via hacs

My Config: 
```
media_art_background:
  blur: 10px
  entities:
    - media_player.spotify
    - entity: media_player.spotify
      image_attribute: entity_picture
      valid_states:
        - playing
  opacity: 0.5
  transition_opacity: 2s
```

If you need more Information let me know.

**Comment by TheLastProject** [comment]
Your config is kinda nonsensical because you define the same entity twice, but that's besides the point.

I can reproduce the issue but I don't quite know how to fix it yet because when I manually run the steps the code does it works fine. So it's probably some race condition.

**Comment by Camatobe** [comment]
strange. 
Some interference with some other plugin? 

Thanks for the catch in my config. Wasnt aware of that, maybe some copy paste mistake.

**Comment by TheLastProject** [comment]
Fixed in b891e210c03f8e4222b22d460c7bf9795134a3f8. Was the errors in your log the only issue? Does it otherwise work fine?

**Comment by Camatobe** [comment]
Funny typo :D 

That was the only issue I've encountered so far :) 
Had some stuttering issues with the transition between play and pause, but that was my fault and caused by the double entity in my config :) 

Was just receiving a Push notification for your update from my hass :D
Thanks for the quick fix and your work on this plugin!!
Working fine now, without errors.

**Comment by TheLastProject** [comment]
Thanks for the kind words and your patience :)
